### ISSUE TITLE
Dockerfile ARG NUMPY_VERSION behavior needs extra --build-arg

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/sostrades-dev-tools#11]
It could be I'm using a "too new" version of Docker, but the declaration of NUMPY_VERSION in dockers/ontology/Dockerfile is failing to propagate to the build process.  Adding `--build-arg NUMPY_VERSION="1.24.4"` to `docker build` does the trick.

**Comment by ggoyon** [comment]
Thank you for the feedback, it has been patched in https://github.com/os-climate/sostrades-dev-tools/commit/1d6368e9154e67caaa03d98302a6d2bad61fa526
